 .sub file Subbasin: 2 9/18/2026 12:00:00 AM ArcSWAT 2012.10_0.14
        5.000000    | SUB_KM : synthetic test value
Section 3
Section 4
Section 5
Section 6
Section 7
Section 8
Section 9
Section 10
Section 11
Section 12
Section 13
Section 14
Section 15
Section 16
Section 17
Section 18
Section 19
Section 20
Section 21
Section 22
Section 23
Section 24
       25.250000    | CH_L1 : synthetic test value
       26.250000    | CH_S1 : synthetic test value
       27.250000    | CH_W1 : synthetic test value
       28.250000    | CH_K1 : synthetic test value
       29.250000    | CH_N1 : synthetic test value
Section 30
Section 31
Section 32
Section 33
Section 34
       35.250000    | CO2 : synthetic test value
Section 36
Section 37
Section 38
Section 39
Section 40
